title: '레진 기술 블로그'
email: tech@lezhin.com
description: '모두를 즐겁게 하라! Amuse Everyone!'
url: 'https://tech.lezhin.com'
enforce_ssl: 'tech.lezhin.com'
baseurl: ''
image: '/assets/img/lezhin_profile.png'
timezone: Asia/Seoul
date_format: "%Y-%m-%d"

repository: lezhin/lezhin.github.io

permalink: /:year/:month/:day/:title

excerpt_separator: <!--more-->

markdown: kramdown

kramdown:
  input: GFM
  highlighter: rouge

gems:
  - jekyll-paginate

paginate: 5
paginate_path: "/pages/:num/"

exclude:
  - README.md
keep_files:
  - assets
  - files
asset_url: /assets

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag
  - scope:
      path: 'oss'
    values:
      layout: page
      sitemap: true
  - scope:
      path: 'recruit'
    values:
      layout: recruit
      sitemap: false

google_analytics_ua: UA-100323260-1
github_username: lezhin
twitter_username: LezhinTech
facebook_username: LezhinTech
